#168362867 Mentor can decline session request
JackieBinya/free-mentors-challenge-final pull request #12
Opened 2019-09-11 11:59 UTC by JackieBinya

#### What does this PR do?
- modifies *server/src/v1/controllers/sessionsController.js/*
- modifies  *server/src/v1/models/Session.js*
- modifies *server/src/v1/tests/sessions.test.js*

#### Description of Task to be completed
- modifies middleware,  model utility functions, controller functions and unit tests associated with the endpoint *POST /api/v1/sessions/:sessionId/reject*

#### How should this be manually tested?
- clone this repo
- create a .env file and add all environmental variables listed in the .env.sample file
- navigate to the git branch *ft-reject-168362867*
- on the terminal run the command *npm test*, to run all unit tests associated with the endpoint *POST /api/v1/sessions/:sessionId/reject*
- on Postman test the route *POST /api/v1/sessions/:sessionId/reject*

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
[#168362867](https://www.pivotaltracker.com/n/projects/2382168)

#### Screenshots (if appropriate)
![Screenshot (363)](https://user-images.githubusercontent.com/50267279/64695382-45a5ef00-d49c-11e9-897d-7d00c3b6fb97.png)

2019-09-11 12:05 UTC, oesukam requested changes

2019-09-11 12:05 UTC, oesukam commented on server/src/v1/middleware/verify.js
> +export default Verify;
Blank line required

2019-09-11 15:36 UTC, JackieBinya commented on server/src/v1/middleware/verify.js
> +export default Verify;
Resolved

2019-09-12 07:04 UTC, oesukam approved these changes

2019-09-12 07:18 UTC, merged